# Generated by Django 2.2.6 on 2021-05-05 13:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogs', '0010_gallery_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=500, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(default='', max_length=2000, verbose_name='Текст отзыва')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Создан')),
                ('allergenicity', models.PositiveIntegerField(default=3, verbose_name='Аллергенность')),
                ('molt', models.PositiveIntegerField(default=3, verbose_name='Линька')),
                ('intelligence', models.PositiveIntegerField(default=3, verbose_name='Интеллект')),
                ('sociability', models.PositiveIntegerField(default=3, verbose_name='Общительность')),
                ('need_for_care', models.PositiveIntegerField(default=3, verbose_name='Потребность в уходе')),
                ('activity', models.PositiveIntegerField(default=3, verbose_name='Активность')),
                ('friendliness', models.PositiveIntegerField(default=3, verbose_name='Дружелюбие')),
                ('health', models.PositiveIntegerField(default=3, verbose_name='Здоровье')),
                ('active', models.BooleanField(default=True, verbose_name='Статус активности')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='catalogs.Breed', verbose_name='Порода')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='feedback', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'db_table': 'feedback',
            },
        ),
    ]
