# Generated by Django 2.2.6 on 2021-04-11 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_type', models.CharField(choices=[('cat', 'Кошка'), ('dog', 'Собака')], default='cat', max_length=30, verbose_name='Вид питомца')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название породы')),
                ('short_description', models.TextField(default='', max_length=2000, verbose_name='Краткое описание')),
                ('origin', models.TextField(default='', max_length=2000, verbose_name='Происхождение')),
                ('character', models.TextField(default='', max_length=2000, verbose_name='Характер и повадки')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='badges/', verbose_name='Изображение')),
                ('allergenicity', models.PositiveIntegerField(choices=[(1, 'Очень низкая'), (2, 'Низкая'), (3, 'Средняя'), (4, 'Высокая'), (5, 'Очень высокая')], default=3, verbose_name='Аллергенность')),
                ('molt', models.PositiveIntegerField(choices=[(1, 'Очень низкая'), (2, 'Низкая'), (3, 'Средняя'), (4, 'Высокая'), (5, 'Очень высокая')], default=3, verbose_name='Линька')),
                ('intelligence', models.PositiveIntegerField(choices=[(1, 'Очень низкий'), (2, 'Низкий'), (3, 'Средний'), (4, 'Высокий'), (5, 'Очень высокий')], default=3, verbose_name='Интеллект')),
                ('sociability', models.PositiveIntegerField(choices=[(1, 'Очень низкая'), (2, 'Низкая'), (3, 'Средняя'), (4, 'Высокая'), (5, 'Очень высокая')], default=3, verbose_name='Общительность')),
                ('need_for_care', models.PositiveIntegerField(choices=[(1, 'Очень низкая'), (2, 'Низкая'), (3, 'Средняя'), (4, 'Высокая'), (5, 'Очень высокая')], default=3, verbose_name='Потребность в уходе')),
                ('activity', models.PositiveIntegerField(choices=[(1, 'Очень низкая'), (2, 'Низкая'), (3, 'Средняя'), (4, 'Высокая'), (5, 'Очень высокая')], default=3, verbose_name='Активность')),
                ('friendliness', models.PositiveIntegerField(choices=[(1, 'Очень низкое'), (2, 'Низкое'), (3, 'Среднее'), (4, 'Высокое'), (5, 'Очень высокое')], default=3, verbose_name='Дружелюбие')),
                ('health', models.PositiveIntegerField(choices=[(1, 'Очень плохое'), (2, 'Плохое'), (3, 'Среднее'), (4, 'Хорошее'), (5, 'Очень хорошее')], default=3, verbose_name='Здоровье')),
                ('active', models.BooleanField(default=True, verbose_name='Статус активности')),
            ],
            options={
                'verbose_name': 'Порода',
                'verbose_name_plural': 'Породы',
                'db_table': 'breed',
            },
        ),
        migrations.CreateModel(
            name='HistoricalBreed',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('pet_type', models.CharField(choices=[('cat', 'Кошка'), ('dog', 'Собака')], default='cat', max_length=30, verbose_name='Вид питомца')),
                ('title', models.CharField(default='', max_length=255, verbose_name='Название породы')),
                ('short_description', models.TextField(default='', max_length=2000, verbose_name='Краткое описание')),
                ('origin', models.TextField(default='', max_length=2000, verbose_name='Происхождение')),
                ('character', models.TextField(default='', max_length=2000, verbose_name='Характер и повадки')),
                ('image', models.TextField(blank=True, max_length=100, null=True, verbose_name='Изображение')),
                ('allergenicity', models.PositiveIntegerField(choices=[(1, 'Очень низкая'), (2, 'Низкая'), (3, 'Средняя'), (4, 'Высокая'), (5, 'Очень высокая')], default=3, verbose_name='Аллергенность')),
                ('molt', models.PositiveIntegerField(choices=[(1, 'Очень низкая'), (2, 'Низкая'), (3, 'Средняя'), (4, 'Высокая'), (5, 'Очень высокая')], default=3, verbose_name='Линька')),
                ('intelligence', models.PositiveIntegerField(choices=[(1, 'Очень низкий'), (2, 'Низкий'), (3, 'Средний'), (4, 'Высокий'), (5, 'Очень высокий')], default=3, verbose_name='Интеллект')),
                ('sociability', models.PositiveIntegerField(choices=[(1, 'Очень низкая'), (2, 'Низкая'), (3, 'Средняя'), (4, 'Высокая'), (5, 'Очень высокая')], default=3, verbose_name='Общительность')),
                ('need_for_care', models.PositiveIntegerField(choices=[(1, 'Очень низкая'), (2, 'Низкая'), (3, 'Средняя'), (4, 'Высокая'), (5, 'Очень высокая')], default=3, verbose_name='Потребность в уходе')),
                ('activity', models.PositiveIntegerField(choices=[(1, 'Очень низкая'), (2, 'Низкая'), (3, 'Средняя'), (4, 'Высокая'), (5, 'Очень высокая')], default=3, verbose_name='Активность')),
                ('friendliness', models.PositiveIntegerField(choices=[(1, 'Очень низкое'), (2, 'Низкое'), (3, 'Среднее'), (4, 'Высокое'), (5, 'Очень высокое')], default=3, verbose_name='Дружелюбие')),
                ('health', models.PositiveIntegerField(choices=[(1, 'Очень плохое'), (2, 'Плохое'), (3, 'Среднее'), (4, 'Хорошее'), (5, 'Очень хорошее')], default=3, verbose_name='Здоровье')),
                ('active', models.BooleanField(default=True, verbose_name='Статус активности')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Порода',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='GenderSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('m', 'Самец'), ('f', 'Самка')], default='m', max_length=1, verbose_name='Пол')),
                ('body_length_min', models.PositiveIntegerField(default=30, verbose_name='Длина от, см')),
                ('body_length_max', models.PositiveIntegerField(default=50, verbose_name='Длина до, см')),
                ('body_height_min', models.PositiveIntegerField(default=10, verbose_name='Высота от, см')),
                ('body_height_max', models.PositiveIntegerField(default=30, verbose_name='Высота до, см')),
                ('body_weight_min', models.PositiveIntegerField(default=10, verbose_name='Вес от, кг')),
                ('body_weight_max', models.PositiveIntegerField(default=30, verbose_name='Вес до, кг')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.Breed', verbose_name='Порода')),
            ],
            options={
                'verbose_name': 'Гендерная особенность',
                'verbose_name_plural': 'Гендерные особенности',
                'db_table': 'gender_spec',
            },
        ),
        migrations.CreateModel(
            name='EyeColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('grey', 'Серые'), ('green', 'Зеленые'), ('blue', 'Голубые'), ('brown', 'Коричневые'), ('black', 'Черные')], default='grey', max_length=30, verbose_name='Цвет')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.Breed', verbose_name='Порода')),
            ],
            options={
                'verbose_name': 'Цвет глаз',
                'verbose_name_plural': 'Цвета глаз',
                'db_table': 'eye_color',
            },
        ),
        migrations.CreateModel(
            name='CoatColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('grey', 'Серый'), ('white', 'Белый'), ('blue', 'Голубой'), ('brown', 'Коричневый'), ('black', 'Черный')], default='grey', max_length=30, verbose_name='Цвет')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogs.Breed', verbose_name='Порода')),
            ],
            options={
                'verbose_name': 'Окрас шерсти',
                'verbose_name_plural': 'Окрасы шерсти',
                'db_table': 'coat_color',
            },
        ),
    ]
