# Generated by Django 2.2.6 on 2021-04-17 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genderspec',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gender_spec', to='catalogs.Breed', verbose_name='Порода'),
        ),
    ]
