# Generated by Django 2.2.6 on 2021-04-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0003_auto_20210417_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='alias',
            field=models.CharField(default='alias', max_length=255, verbose_name='Псевдоним (транслит)'),
        ),
        migrations.AddField(
            model_name='historicalbreed',
            name='alias',
            field=models.CharField(default='alias', max_length=255, verbose_name='Псевдоним (транслит)'),
        ),
    ]
