# Generated by Django 2.2.6 on 2021-04-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0004_auto_20210418_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eyecolor',
            name='color',
            field=models.CharField(choices=[('grey', 'Серые'), ('green', 'Зелёные'), ('blue', 'Голубые'), ('brown', 'Коричневые'), ('black', 'Чёрные'), ('yellow', 'Жёлтые')], default='grey', max_length=30, verbose_name='Цвет'),
        ),
    ]
