# Generated by Django 2.2.6 on 2021-04-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0005_auto_20210418_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='breed',
            name='full_description',
            field=models.TextField(default='', max_length=2000, verbose_name='Полное описание'),
        ),
        migrations.AddField(
            model_name='historicalbreed',
            name='full_description',
            field=models.TextField(default='', max_length=2000, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='short_description',
            field=models.TextField(default='', max_length=64, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='historicalbreed',
            name='short_description',
            field=models.TextField(default='', max_length=64, verbose_name='Краткое описание'),
        ),
    ]
