# Generated by Django 2.2.6 on 2021-04-23 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0007_auto_20210423_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='short_description',
            field=models.TextField(default='', max_length=256, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='historicalbreed',
            name='short_description',
            field=models.TextField(default='', max_length=256, verbose_name='Краткое описание'),
        ),
    ]
