# Generated by Django 2.2.6 on 2021-05-04 07:46

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0008_auto_20210423_0919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(upload_to='gallery/', verbose_name='Изображение')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='catalogs.Breed', verbose_name='Порода')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
                'db_table': 'gallery',
            },
        ),
    ]
