# Generated by Django 2.2.6 on 2021-05-06 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0010_gallery_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coatcolor',
            name='color',
        ),
        migrations.AddField(
            model_name='breed',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Код породы'),
        ),
        migrations.AddField(
            model_name='breed',
            name='wcf',
            field=models.PositiveIntegerField(choices=[(1, 'Длинношёрстные'), (2, 'Полудлинношерстные'), (3, 'Короткошёрстные'), (4, 'Сиамо-Ориентальная короткошёрстные')], default=1, verbose_name='Группа породы по WCF'),
        ),
        migrations.AddField(
            model_name='coatcolor',
            name='amount_of_white',
            field=models.CharField(blank=True, choices=[('01', 'Ван'), ('02', 'Арлекин'), ('03', 'Биколор'), ('04', 'Миттед'), ('05', 'Сноу-шу'), ('09', 'Любое другое количество белого')], max_length=30, null=True, verbose_name='Количество белого'),
        ),
        migrations.AddField(
            model_name='coatcolor',
            name='base_color',
            field=models.CharField(choices=[('n', 'Чёрный'), ('a', 'Голубой'), ('b', 'Шоколадный'), ('c', 'Лиловый'), ('d', 'Красный'), ('e', 'Кремовый'), ('f', 'Черный черепаховый'), ('g', 'Голубой черепаховый'), ('h', 'Шоколадный черепаховый'), ('j', 'Лиловый черепаховый'), ('o', 'Циннамон, соррель'), ('p', 'Фавн'), ('q', 'Циннамон черепаховый'), ('r', 'Фавн черепаховый'), ('w', 'Белый'), ('nt', 'Янтарный'), ('at', 'Светло-янтарный'), ('dt', 'Красный-янтарный'), ('et', 'Кремовый-янтарный'), ('ft', 'Янтарный черепаховый'), ('gt', 'Светло-янтарный черепаховый')], default='n', max_length=30, verbose_name='Основной цвет'),
        ),
        migrations.AddField(
            model_name='coatcolor',
            name='dilute_modifier',
            field=models.CharField(blank=True, choices=[('m', 'Модификатор'), ('am', 'Карамельный, на голубой основе'), ('cm', 'Карамельный, на лиловой основе или серо-коричневый'), ('em', 'Абрикосовый, на кремовой основе'), ('pm', 'Карамель, на фавн основе'), ('gm', 'Карамельный черепаховый, карамельный, на голубой основе черепаховый'), ('jm', 'Карамельный, на голубой основе черепаховый или серо-коричневый черепаховый'), ('rm', 'Карамель, на фавн основе черепаховый'), ('*m', 'Карамель, с неизвестной основой')], max_length=30, null=True, verbose_name='Модификатор осветления'),
        ),
        migrations.AddField(
            model_name='coatcolor',
            name='pointed_pattern',
            field=models.CharField(blank=True, choices=[('31', 'Бурманские отметины'), ('32', 'Тонкинские отметины'), ('33', 'Сиамские отметины'), ('34', 'Сингапурский окрас'), ('35', 'Абиссинский окрас')], max_length=30, null=True, verbose_name='Пойнтовые отметины'),
        ),
        migrations.AddField(
            model_name='coatcolor',
            name='silver_gold',
            field=models.CharField(blank=True, choices=[('s', 'Серебро'), ('y', 'Золото')], max_length=30, null=True, verbose_name='Серебро/золото'),
        ),
        migrations.AddField(
            model_name='coatcolor',
            name='tabby_pattern',
            field=models.CharField(blank=True, choices=[('11', 'Затушеванный'), ('12', 'Завуалированный'), ('21', 'Табби без определенного рисунка'), ('22', 'Мраморный табби'), ('23', 'Тигровый табби'), ('24', 'Пятнистый табби'), ('25', 'Тикированный табби')], max_length=30, null=True, verbose_name='Табби рисунок'),
        ),
        migrations.AddField(
            model_name='historicalbreed',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Код породы'),
        ),
        migrations.AddField(
            model_name='historicalbreed',
            name='wcf',
            field=models.PositiveIntegerField(choices=[(1, 'Длинношёрстные'), (2, 'Полудлинношерстные'), (3, 'Короткошёрстные'), (4, 'Сиамо-Ориентальная короткошёрстные')], default=1, verbose_name='Группа породы по WCF'),
        ),
        migrations.AlterField(
            model_name='eyecolor',
            name='color',
            field=models.IntegerField(choices=[(61, 'Голубой'), (62, 'Оранжевый, желтый, золотистый'), (63, 'Разный цвет глаз, разноглазие'), (64, 'Зеленый'), (65, 'Цвет глаз бурманских кошек'), (66, 'Цвет глаз тонкинских кошек'), (67, 'Цвет глаз сиамских кошек')], default='grey', verbose_name='Цвет'),
        ),
    ]
