# Generated by Django 2.2.6 on 2021-05-16 15:31

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0011_auto_20210506_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='character',
            field=djrichtextfield.models.RichTextField(default='', max_length=2000, verbose_name='Характер и повадки'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='full_description',
            field=djrichtextfield.models.RichTextField(default='', max_length=2000, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='origin',
            field=djrichtextfield.models.RichTextField(default='', max_length=2000, verbose_name='Происхождение'),
        ),
        migrations.AlterField(
            model_name='historicalbreed',
            name='character',
            field=djrichtextfield.models.RichTextField(default='', max_length=2000, verbose_name='Характер и повадки'),
        ),
        migrations.AlterField(
            model_name='historicalbreed',
            name='full_description',
            field=djrichtextfield.models.RichTextField(default='', max_length=2000, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='historicalbreed',
            name='origin',
            field=djrichtextfield.models.RichTextField(default='', max_length=2000, verbose_name='Происхождение'),
        ),
    ]
